// Evidence-backed numbers shown in the demo. Generated by repository commands:
//   npm run demo:data
// which runs `npm run build`, then tools/measure-metrics.mjs and
// tools/measure-bench.mjs. Nothing here is hand-typed.
import metricsJson from "../data/metrics.json";
import benchJson from "../data/bench.json";

export interface Metrics {
  generatedBy: string;
  distribution: { chiSquare: number; df: number; samples: number };
  proximity: { close: number; pairs: number };
  stability: {
    checks: number;
    corpusSize: number;
    optionCases: number;
    determinismMismatches: number;
    cssIdentityMismatches: number;
    rgbDomainViolations: number;
  };
  gamut: { samples: number; outOfGamut: number };
  size: {
    coreGzipBytes: number;
    coreGzipKib: number;
    paletteGzipBytes: number;
    paletteGzipKib: number;
  };
  calibration: {
    status: string;
    note: string;
    kHk: number;
    hkPeakHue: number;
    darkLightnessShift: number;
    darkLightnessCap: number;
    darkChromaScale: number;
    distinctThreshold: number;
    hkActive: boolean;
    darkVariantLiftsLightness: boolean;
    darkVariantMutesChroma: boolean;
  };
}

export interface Bench {
  generatedBy: string;
  node: string;
  hexNsPerOp: number;
  hexOpsPerSec: number;
}

export const metrics = metricsJson as Metrics;
export const bench = benchJson as Bench;

export const MOOD_NAMES = ["balanced", "pastel", "vibrant", "jewel", "earth", "neon"] as const;
export type MoodName = (typeof MOOD_NAMES)[number];

// Moods whose chroma is sampled relative to each hue's gamut limit rather than as
// a uniform absolute value. Mirrors `chromaMode` in src/moods.ts so the demo can
// describe a set honestly when the mood selector changes.
const RELATIVE_CHROMA_MOODS: ReadonlySet<string> = new Set(["vibrant", "jewel", "neon"]);

export function isRelativeChroma(mood: string): boolean {
  return RELATIVE_CHROMA_MOODS.has(mood);
}

function formatThousands(value: number): string {
  return value.toLocaleString("en-US");
}

// A few derived strings the hero and comparison reuse.
export const facts = {
  latency: `${Math.round(bench.hexNsPerOp)} ns`,
  opsPerSec: `${(bench.hexOpsPerSec / 1_000_000).toFixed(1)}M`,
  chiSquare: Math.round(metrics.distribution.chiSquare).toString(),
  chiSamples: formatThousands(metrics.distribution.samples),
  gamut: `${metrics.gamut.outOfGamut} / ${formatThousands(metrics.gamut.samples)}`,
  coreSize: `${metrics.size.coreGzipKib} KB`,
  paletteSize: `${metrics.size.paletteGzipKib} KB`,
};
